<?php 	
	include_once("../Pos/trunk/server/cliente.php");
	include_once("../Pos/trunk/server/compra.php");
	include_once("../Pos/trunk/server/cotizacion.php");
	include_once("../Pos/trunk/server/cuenta_cliente.php");
	include_once("../Pos/trunk/server/cuenta_proveedor.php");
	include_once("../Pos/trunk/server/detalle_compra.php");
	include_once("../Pos/trunk/server/detalle_cotizacion.php");
	include_once("../Pos/trunk/server/detalle_inventario.php");
	include_once("../Pos/trunk/server/detalle_venta.php");
	include_once("../Pos/trunk/server/factura_compra.php");
	include_once("../Pos/trunk/server/factura_venta.php");
	include_once("../Pos/trunk/server/impuesto.php");
	include_once("../Pos/trunk/server/inventario.php");
	include_once("../Pos/trunk/server/nota_remision.php");
	include_once("../Pos/trunk/server/pagos_compra.php");
	include_once("../Pos/trunk/server/pagos_venta.php");
	include_once("../Pos/trunk/server/productos_proveedor.php");
	include_once("../Pos/trunk/server/proveedor.php");
	include_once("../Pos/trunk/server/sucursal.php");
	include_once("../Pos/trunk/server/usuario.php");
	include_once("../Pos/trunk/server/venta.php"); 
	include_once("../Pos/trunk/server/listar.php"); 
?>