
Aplicacion.Efectivo=function(){return this._init();}
Aplicacion.Efectivo.prototype._init=function(){if(DEBUG){console.log("Efectivo: construyendo");}
this.cargarSucursales();this.nuevoGastoPanelCreator();this.nuevoIngresoPanelCreator();Aplicacion.Efectivo.currentInstance=this;return this;};Aplicacion.Efectivo.prototype.getConfig=function(){return{text:'Efectivo',cls:'launchscreen',items:[{text:'Gasto',card:this.nuevoGastoPanel,leaf:true},{text:'Ingresos',card:this.nuevoIngresoPanel,leaf:true}]};};Aplicacion.Efectivo.prototype.sucursalesLista=null;Aplicacion.Efectivo.prototype.cargarSucursales=function()
{Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:700},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!r.success){return;}
if(DEBUG){console.log("----r datos-----");console.log(r.datos);console.log("---------");}
sucursales=[{text:"Seleccione una sucursal de la lista",value:""}];for(var i=0;i<r.datos.length;i++){sucursales.push({text:r.datos[i].descripcion,value:r.datos[i].id_sucursal});}
Aplicacion.Efectivo.currentInstance.sucursalesLista=sucursales;},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.gastosFijos=null;Aplicacion.Efectivo.prototype.cargarGastosFijos=function()
{Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:610},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!r.success){return;}
if(DEBUG){console.log("----r data-----");console.log(r.data);console.log("---------");}
var gastos=[{text:"Seleccione un gasto de la lista",value:""}];for(var i=0;i<r.data.length;i++){gastos.push({text:r.data[i].text,value:r.data[i].value});}
gastos.push({text:"Otro",value:"otros"});Aplicacion.Efectivo.currentInstance.gastosFijos=gastos;},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.cargarEmpleados=function(a,b)
{Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:505,id_sucursal:b},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!r.success){return;}
Ext.getCmp("Efectivo-operacionInterSucursalEfectivo-responsable").setOptions(r.datos);},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.nuevoGastoValidator=function()
{var values=Aplicacion.Efectivo.currentInstance.nuevoGastoPanel.getValues();if(!(values.monto&&/^-?\d+(\.\d+)?$/.test(values.monto+''))){Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-monto'),'fade',{duration:250,out:true,autoClear:true});return;}
if(Ext.getCmp('Efectivo-nuevoGastoPanel-folio').isVisible())
{if(values.folio.length==0)
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-folio'),'fade',{duration:250,out:true,autoClear:true});return;}}
else
{if(values.nota.length==0)
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-nota'),'fade',{duration:250,out:true,autoClear:true});return;}}
if(!values.fecha)
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-fecha'),'fade',{duration:250,out:true,autoClear:true});return;}
if(Ext.getCmp('Efectivo-nuevoGastoPanel-concepto').getValue()==""){Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-concepto'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Efectivo.currentInstance.nuevoGasto(values);};Aplicacion.Efectivo.prototype.nuevoGasto=function(data){Ext.getBody().mask('Guardando nuevo gasto ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:600,data:Ext.util.JSON.encode(data)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();Aplicacion.Efectivo.currentInstance.nuevoGastoPanel.reset();if(!Ext.getCmp('Efectivo-nuevoGastoPanel-folio').isVisible())
{Ext.getCmp('Efectivo-nuevoGastoPanel-folio').show();Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-folio'),'slide',{duration:500,out:false,autoClear:false});}
if(r.success=="true")
{Ext.Msg.alert("Efectivo","Se ha registrado el nuevo gasto");}
else
{Ext.Msg.alert("Efectivo","Error: "+r.success);}},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.nuevoGastoPanel=null;Date.monthNames=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];Aplicacion.Efectivo.prototype.nuevoGastoPanelCreator=function(){this.nuevoGastoPanel=new Ext.form.FormPanel({listeners:{"show":function(){Ext.getCmp("Efectivo-nuevoGastoPanel-concepto").setOptions(Aplicacion.Efectivo.currentInstance.gastosFijos);}},items:[{xtype:'fieldset',title:'Ingrese los detalles del nuevo gasto',instructions:'Si desea agregar un gasto que no se encuentre en la lista debera pedir una autorizacion.',items:[new Ext.form.Text({id:'Efectivo-nuevoGastoPanel-monto',name:'monto',label:'Monto',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:Aplicacion.Efectivo.currentInstance.nuevoGastoValidator};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Efectivo-nuevoGastoPanel-folio',name:'folio',label:'Folio',required:true,listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar',callback:Aplicacion.Efectivo.currentInstance.nuevoGastoValidator};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.DatePicker({id:'Efectivo-nuevoGastoPanel-fecha',name:'fecha',label:'Fecha',picker:{yearFrom:2010,yearTo:2011},required:true}),new Ext.form.Select({id:'Efectivo-nuevoGastoPanel-concepto',name:'concepto',label:'Concepto',required:true,listeners:{"change":function(){if(this.value=="otros")
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-folio'),'slide',{duration:500,out:true,autoClear:false,after:function(){Ext.getCmp('Efectivo-nuevoGastoPanel-folio').setValue("");Ext.getCmp('Efectivo-nuevoGastoPanel-folio').hide()}});}
else if(!Ext.getCmp('Efectivo-nuevoGastoPanel-folio').isVisible())
{Ext.getCmp('Efectivo-nuevoGastoPanel-folio').show();Ext.Anim.run(Ext.getCmp('Efectivo-nuevoGastoPanel-folio'),'slide',{duration:500,out:false,autoClear:false});}}}}),new Ext.form.Text({id:'Efectivo-nuevoGastoPanel-nota',name:'nota',label:'Nota',listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),]},new Ext.Button({id:'Efectivo-NuevoGasto',ui:'action',text:'Registrar Gasto',margin:5,handler:this.nuevoGastoValidator,disabled:false})]});};Aplicacion.Efectivo.prototype.nuevoAbonoValidator=function()
{var values=Aplicacion.Efectivo.currentInstance.nuevoAbonoPanel.getValues();if(!(values.monto&&/^-?\d+(\.\d+)?$/.test(values.monto+''))){Ext.Anim.run(Ext.getCmp('Efectivo-nuevoAbonoPanel-monto'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Efectivo.currentInstance.nuevoAbono(values);};Aplicacion.Efectivo.prototype.nuevoAbono=function(data){Ext.Msg.alert("Efectivo","Guardando el nuevo abono");Ext.getBody().mask('Guardando nuevo abono ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:606,data:Ext.util.JSON.encode(data)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();Aplicacion.Efectivo.currentInstance.nuevoAbonoPanel.reset();if(r.success=="true")
{Ext.Msg.alert("Efectivo","Se ha registrado el nuevo abono");}
else
{Ext.Msg.alert("Efectivo","Error: "+r.success);}},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.nuevoIngresoValidator=function()
{var values=Aplicacion.Efectivo.currentInstance.nuevoIngresoPanel.getValues();if(!(values.monto&&/^-?\d+(\.\d+)?$/.test(values.monto+''))){Ext.Anim.run(Ext.getCmp('Efectivo-nuevoIngresoPanel-monto'),'fade',{duration:250,out:true,autoClear:true});return;}
if(!values.fecha)
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoIngresoPanel-fecha'),'fade',{duration:250,out:true,autoClear:true});return;}
if(values.concepto.length<3)
{Ext.Anim.run(Ext.getCmp('Efectivo-nuevoIngresoPanel-concepto'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Efectivo.currentInstance.nuevoIngreso(values);};Aplicacion.Efectivo.prototype.nuevoIngreso=function(data){Ext.getBody().mask('Guardando nuevo ingreso ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:603,data:Ext.util.JSON.encode(data)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();Aplicacion.Efectivo.currentInstance.nuevoIngresoPanel.reset();Ext.Msg.alert("Efectivo","Se ha registrado el nuevo ingreso");},failure:function(response){POS.error(response);}});};Aplicacion.Efectivo.prototype.nuevoIngresoPanel=null;Aplicacion.Efectivo.prototype.nuevoIngresoPanelCreator=function(){this.nuevoIngresoPanel=new Ext.form.FormPanel({items:[{xtype:'fieldset',title:'Ingrese los detalles del nuevo ingreso',instructions:'Si desea agregar un gasto que no se encuentre en la lista debera pedir una autorizacion.',items:[new Ext.form.Text({id:'Efectivo-nuevoIngresoPanel-monto',name:'monto',label:'Monto',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.DatePicker({id:'Efectivo-nuevoIngresoPanel-fecha',name:'fecha',label:'Fecha',picker:{yearFrom:2010,yearTo:2011},required:true}),new Ext.form.Text({id:'Efectivo-nuevoIngresoPanel-concepto',name:'concepto',label:'Concepto',required:true,listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Efectivo-nuevoIngresoPanel-nota',name:'nota',label:'Nota',listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),]},new Ext.Button({id:'Efectivo-NuevoIngreso',ui:'action',text:'Registrar Ingreso',margin:5,handler:this.nuevoIngresoValidator,disabled:false})]});};POS.Apps.push(new Aplicacion.Efectivo());Aplicacion.Operaciones=function(){return this._init();}
Aplicacion.Operaciones.prototype._init=function(){if(DEBUG){console.log("Operaciones: construyendo");}
Aplicacion.Operaciones.currentInstance=this;Aplicacion.Operaciones.currentInstance.cancelarVentaPanelCreator();Aplicacion.Operaciones.currentInstance.prestamoEfectivoPanelCreator();Aplicacion.Operaciones.currentInstance.abonarPrestamoEfectivoSucursalPanelCreator();Aplicacion.Operaciones.currentInstance.listaDePrestamosSucursalLoad();Aplicacion.Operaciones.currentInstance.finishedPanelCreator();return this;};Aplicacion.Operaciones.prototype.getConfig=function(){return{text:'Prestamos Intersucursal',cls:'launchscreen',items:[{text:'Abono a Prestamo',card:Aplicacion.Operaciones.currentInstance.abonarPrestamoEfectivoSucursalPanel,leaf:true},{text:'Prestar efectivo',card:Aplicacion.Operaciones.currentInstance.prestamoEfectivoPanel,leaf:true},{text:'Cancelar venta',card:Aplicacion.Operaciones.currentInstance.cancelarVentaPanel,leaf:true}]};};Aplicacion.Operaciones.prototype.venta={id_venta:null,cliente:null};Aplicacion.Operaciones.prototype.cancelarVentaPanelUpdater=function(){Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:803},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(r.success==false){Aplicacion.Operaciones.currentInstance.venta.id_venta=null;Aplicacion.Operaciones.currentInstance.venta.cliente=null;var html="<div style='margin-top:20px; margin-bottom:10px;position:relative; width:100%; color: #333; font-weight: bold;text-shadow: white 0px 1px 1px;left:5px; position:relative;float:left;' >No se tiene registro de ninguna venta. </div>";Ext.getCmp('Operaciones-cancelarVentaPanel-Tabla').update(html);Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Cliente').setValue("");Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Subtotal').setValue("");Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Descuento').setValue(POS.currencyFormat(""));Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Total').setValue(POS.currencyFormat(""));}
Aplicacion.Operaciones.currentInstance.venta.id_venta=r.id_venta;Aplicacion.Operaciones.currentInstance.venta.cliente=r.cliente;var html="<div style='margin-top:20px; margin-bottom:10px;position:relative; width:100%; color: #333; font-weight: bold;text-shadow: white 0px 1px 1px;left:5px; position:relative;float:left;' > Detalle de la venta  "+r.id_venta+" </div>";html+="<table border=0 style = 'margin-top:10px;' >";html+="<tr class='top'>";html+="<td align='center'>Descripcion</td>";html+="<td align='center'>Cantidad Original</td>";html+="<td align='center' >Precio Original</td>";html+="<td align='center'>Cantidad  Procesado</td>";html+="<td align='center' >Precio Procesado</td>";html+="<td align='center' >Sub Total</td>";html+="</tr>";detalle_venta=r.detalle_venta;subtotal=0;for(var i=0;i<detalle_venta.length;i++){if(i==detalle_venta.length-1){html+="<tr class='last'>";}else{html+="<tr >";}
html+="<td style='width: 30%;' ><b>"+detalle_venta[i].id_producto+"</b> "+detalle_venta[i].descripcion+"</td>";html+="<td  align='center' style='width: 14%;'> "+detalle_venta[i].cantidad+"  </td>";html+="<td  align='center'  style='width: 14%;'> "+detalle_venta[i].precio+"  </td>";html+="<td  align='center'  style='width: 14%;' > "+detalle_venta[i].cantidad_procesada+"  </td>";html+="<td  align='center'  style='width: 14%;'> "+detalle_venta[i].precio_procesada+" </td>";_subtotal=(detalle_venta[i].cantidad*detalle_venta[i].precio)+(detalle_venta[i].cantidad_procesada*detalle_venta[i].precio_procesada);subtotal+=_subtotal;html+="<td  align='center'  style='width: 14%;'> "+POS.currencyFormat(_subtotal)+" </td>";html+="</tr>";}
var descuento=(subtotal*r.cliente.descuento/100);html+="</table>";Ext.getCmp('Operaciones-cancelarVentaPanel-Tabla').update(html);Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Cliente').setValue(r.cliente.razon_social);Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Subtotal').setValue(POS.currencyFormat(subtotal));Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Descuento').setValue(POS.currencyFormat(descuento));Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Total').setValue(POS.currencyFormat(subtotal-descuento));},failure:function(response){POS.error(response);}});};Aplicacion.Operaciones.prototype.cancelarVentaPanelCreator=function(){this.cancelarVentaPanel=new Ext.Panel({ui:"dark",modal:false,floating:false,scroll:true,id:"Operaciones-cancelarVentaPanel",style:{padding:'10px'},listeners:{"show":function(){Aplicacion.Operaciones.currentInstance.cancelarVentaPanelUpdater();}},items:[{title:"",cls:"Tabla",items:[{id:'Operaciones-cancelarVentaPanel-Tabla',html:"<div style='margin-top:20px; margin-bottom:10px;position:relative; width:100%; color: #333; font-weight: bold;text-shadow: white 0px 1px 1px;left:5px; position:relative;float:left;' >No se tiene registro de ninguna venta. </div>"}]},{xtype:'fieldset',title:'Detalles del Cliente',items:[new Ext.form.Text({name:'nombre',label:'Cliente',id:'Operaciones-cancelarVentaPanel-Form-Cliente'}),new Ext.form.Text({name:'subtotal',label:'Subtotal',id:'Operaciones-cancelarVentaPanel-Form-Subtotal'}),new Ext.form.Text({name:'descuento',label:'Descuento',id:'Operaciones-cancelarVentaPanel-Form-Descuento'}),new Ext.form.Text({name:'total',label:'Total',id:'Operaciones-cancelarVentaPanel-Form-Total'})]},new Ext.Button({ui:'action',text:'Cancelar venta',margin:5,handler:Aplicacion.Operaciones.currentInstance.doCancelarVenta})]});};Aplicacion.Operaciones.prototype.doCancelarVenta=function(){Ext.Msg.confirm("Eliminar Venta","¿Esta usted seguro de que desea eliminar la venta?",function(action){if(action=="yes")
{Aplicacion.Operaciones.currentInstance.eliminarVenta();}});};Aplicacion.Operaciones.prototype.eliminarVenta=function(){Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:804,id_venta:Aplicacion.Operaciones.currentInstance.venta.id_venta},success:function(response,opts){try{informacion=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!informacion.success){if(DEBUG){console.log("obtenicion de la informacion sin exito.");}
if(informacion.info&&informacion.info=="elimination_time"){Ext.Msg.alert("Eliminar Venta",informacion.reason);return;}
var html="<div style='margin-top:20px; margin-bottom:10px;position:relative; width:100%; color: #333; font-weight: bold;text-shadow: white 0px 1px 1px;left:5px; position:relative;float:left;' >No se tiene registro de ninguna venta. </div>";Ext.getCmp('Operaciones-cancelarVentaPanel-Tabla').update(html);Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Cliente').setValue("");Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Subtotal').setValue("");Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Descuento').setValue(POS.currencyFormat(""));Ext.getCmp('Operaciones-cancelarVentaPanel-Form-Total').setValue(POS.currencyFormat(""));return;}
if(DEBUG){console.log("obtenicion de la informacion exitosa ");}
Aplicacion.Operaciones.currentInstance.cancelarVentaPanelUpdater();},failure:function(response){POS.error(response);}});};Aplicacion.Operaciones.prototype.finishedPanel=null;Aplicacion.Operaciones.prototype.finishedPanelCreator=function()
{this.finishedPanel=new Ext.Panel({html:""});};Aplicacion.Operaciones.prototype.finishedPanelShow=function(data_prestamo)
{this.finishedPanelUpdater(data_prestamo);};Aplicacion.Operaciones.prototype.finishedPanelUpdater=function(data_prestamo)
{if(DEBUG){console.log("se mando a imprimir : ",Ext.util.JSON.encode(data_prestamo));}
POS.ajaxToClient({module:"Printer",args:data_prestamo,success:function(r){if(DEBUG){console.log("ticket printing responded",r);}},failure:function(){if(DEBUG){console.warn("client not found !!!",r);}}});html="";html+="<table class='Mostrador-ThankYou' style = 'margin : 0 !important;' >";html+=" <tr>";html+="  <td align = center ><img align = center  src='../media/cash_register.png'></td>";html+=" </tr>";html+=" <tr>";html+="  <td align = center> El prestamo ha sido registrado con exito.. </td>";html+=" </tr>";html+="</table>";this.finishedPanel.update(html);sink.Main.ui.setActiveItem(this.finishedPanel,'fade');};Aplicacion.Operaciones.prototype.finishedPanelCreator=function()
{this.finishedPanel=new Ext.Panel({html:""});};Aplicacion.Operaciones.prototype.prestamoEfectivoPanel=null;Aplicacion.Operaciones.prototype.prestamoEfectivoPanelCreator=function(){this.prestamoEfectivoPanel=new Ext.form.FormPanel({listeners:{"show":function(){Ext.getCmp("Operaciones-prestamoEfectivo-sucursal").setOptions(Aplicacion.Efectivo.currentInstance.sucursalesLista);}},items:[{xtype:'fieldset',title:'Nuevo prestamo de efectivo',instructions:'Todos los campos son necesarios para una nueva autorizacion.',items:[new Ext.form.Select({id:'Operaciones-prestamoEfectivo-sucursal',name:'sucursal',label:'Sucursal',required:true,options:[{text:"Seleccione una sucursal",value:""}]}),new Ext.form.Text({id:'Operaciones-prestamoEfectivo-concepto',label:'Concepto',name:'concepto',required:true,listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Operaciones-prestamoEfectivo-monto',label:'Monto',name:'monto',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Registrar Prestamo de Efectivo',margin:5,handler:this.nuevoPrestamoEfectivoValidator,disabled:false})]});};Aplicacion.Operaciones.prototype.nuevoPrestamoEfectivoValidator=function()
{var values=Aplicacion.Operaciones.currentInstance.prestamoEfectivoPanel.getValues();if(!(values.sucursal!=""))
{Ext.Anim.run(Ext.getCmp('Operaciones-prestamoEfectivo-sucursal'),'fade',{duration:250,out:true,autoClear:true});return;}
if(values.concepto=="")
{Ext.Anim.run(Ext.getCmp('Operaciones-prestamoEfectivo-concepto'),'fade',{duration:250,out:true,autoClear:true});return;}
if(isNaN(parseFloat(values.monto))||parseFloat(values.monto)<=0){Ext.Anim.run(Ext.getCmp('Operaciones-prestamoEfectivo-monto'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Operaciones.currentInstance.nuevaOperacionInterSucursalEfectivo(values);};Aplicacion.Operaciones.prototype.nuevaOperacionInterSucursalEfectivo=function(data){Ext.getBody().mask('Guardando nuevo prestamo de efectivo ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:607,data:Ext.util.JSON.encode(data)},success:function(response,opts){try{prestamo=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();Aplicacion.Operaciones.currentInstance.prestamoEfectivoPanel.reset();if(!prestamo.success)
{Ext.Msg.alert("Operaciones","Error: "+prestamo.reason);}
for(i=0;i<POS.documentos.length;i++){if(POS.documentos[i].documento=='abono_venta_cliente'){var impresora=POS.documentos[i].impresora;break;}}
data_prestamo={ticket:'prestamo_efectivo_sucursal',id_prestamo:prestamo.id_prestamo,empleado:prestamo.empleado,concepto:data.concepto,saldo_prestamo:data.monto,monto:data.monto,sucursal_origen:prestamo.sucursal_origen,sucursal_destino:prestamo.sucursal_destino,leyendasTicket:POS.leyendasTicket,impresora:impresora};if(DEBUG){console.log("Enviando prestamo de efectivo : ",data_prestamo);}
Aplicacion.Operaciones.currentInstance.finishedPanelShow(data_prestamo);},failure:function(response){POS.error(response);}});};Ext.regModel('listaDePrestamosSucursalModel',{fields:[{name:'id_prestamo',type:'int'},{name:'concepto',type:'string'}]});Aplicacion.Operaciones.prototype.listaDePrestamosSucursal={lista:null,lastUpdate:null,hash:null};Aplicacion.Operaciones.prototype.listaDePrestamosSucursalStore=new Ext.data.Store({model:'listaDePrestamosSucursalModel',sorters:'sucursal',getGroupString:function(record){return record.get("sucursal");}});Aplicacion.Operaciones.prototype.listaDePrestamosSucursalLoad=function(){if(DEBUG){console.log("Actualizando lista de autorizaciones ....");}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:609},success:function(response,opts){try{prestamos=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(!prestamos.success){return POS.error(prestamos);}
this.listaDePrestamosSucursal.lista=prestamos.data;this.listaDePrestamosSucursal.lastUpdate=Math.round(new Date().getTime()/1000.0);this.listaDePrestamosSucursal.hash=prestamos.hash;this.listaDePrestamosSucursalStore.loadData(prestamos.data);if(DEBUG){console.log("Lista de prestamos retrived !",prestamos,this.listaDePrestamosSucursalStore);}},failure:function(response){POS.error(response);}});};Aplicacion.Operaciones.prototype.abonarPrestamoEfectivoSucursalPanel=null;Aplicacion.Operaciones.prototype.abonarPrestamoEfectivoSucursalPanelCreator=function(){this.abonarPrestamoEfectivoSucursalPanel=new Ext.Panel({items:[{xtype:'fieldset',title:'Seleccione un prestamo para realizar un abono',items:[{xtype:'list',width:'100%',height:235,emptyText:"vacio",store:this.listaDePrestamosSucursalStore,itemTpl:'<div class="listaDeAutorizacionesAutorizacion">ID del prestamo : {id_prestamo}&nbsp; Concepto :  {concepto}</div>',grouped:true,indexBar:false,listeners:{"selectionchange":function(view,nodos,c){if(nodos.length>0){if(DEBUG){console.log("selecciono realizar abono a : ",nodos[0].data);}
Aplicacion.Operaciones.currentInstance.abonarPrestamosEfectivoSucursalUpdateDetallesPrestamo(nodos[0].data);}
view.deselectAll();}}}]},{xtype:'fieldset',title:'Detalles del prestamo a sucursal',items:[new Ext.form.Text({id:'Operaciones-abonarPrestamoEfectivoSucursal-prestamo',label:'ID Prestamo',name:'prestamo'}),new Ext.form.Text({id:'Operaciones-abonarPrestamoEfectivoSucursal-sucursal',label:'Sucursal',name:'sucursal'}),new Ext.form.Text({id:'Operaciones-abonarPrestamoEfectivoSucursal-saldo',label:'Saldo',name:'saldo'}),new Ext.form.Text({id:'Operaciones-abonarPrestamoEfectivoSucursal-concepto',label:'Concepto',name:'concepto'}),new Ext.form.Text({id:'Operaciones-abonarPrestamoEfectivoSucursal-monto',label:'Monto',name:'monto',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Abonar',margin:5,handler:this.abonarPrestamosEfectivoSucursalValidator,disabled:false})]});};Aplicacion.Operaciones.prototype.abonarPrestamosEfectivoSucursalUpdateDetallesPrestamo=function(prestamo){Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-prestamo').setValue(prestamo.id_prestamo);Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-sucursal').setValue(prestamo.sucursal);Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-concepto').setValue(prestamo.concepto);Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-saldo').setValue(prestamo.saldo);Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-monto').setValue("");};Aplicacion.Operaciones.prototype.abonarPrestamosEfectivoSucursalValidator=function(){var transaccion={monto:null,id_prestamo:null,saldo:null,cambio:null};transaccion.monto=parseFloat(Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-monto').getValue());transaccion.id_prestamo=Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-prestamo').getValue();transaccion.saldo=parseFloat(Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-saldo').getValue());if(transaccion.monto>=transaccion.saldo)
{transaccion.cambio=transaccion.monto-transaccion.saldo;transaccion.monto=transaccion.saldo;transaccion.saldo=parseFloat(0);}
else
{transaccion.cambio=parseFloat(0);transaccion.saldo=transaccion.saldo-transaccion.monto;}
if(isNaN(parseFloat(transaccion.monto))||parseFloat(transaccion.monto)<=0){Ext.Anim.run(Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-monto'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Operaciones.currentInstance.abonarPrestamosEfectivoSucursalNuevoAbono(transaccion);};Aplicacion.Operaciones.prototype.abonarPrestamosEfectivoSucursalNuevoAbono=function(transaccion){if(DEBUG){console.log("Ingresando nuevo Abono a prestamo sucursal..");}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:608,monto:transaccion.monto,id_prestamo:transaccion.id_prestamo},success:function(response,opts){try{abono=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(!abono.success){Ext.Msg.alert("Operaciones",abono.reason);}
if(DEBUG){console.warn("IMPRMIR TICKET");}
Ext.Msg.alert("Operaciones","Abonado: "+POS.currencyFormat(transaccion.monto)+"<br>Su cambio: "+POS.currencyFormat(transaccion.cambio)+"<br>Saldo Pendiente: "+POS.currencyFormat(transaccion.saldo));Aplicacion.Operaciones.currentInstance.listaDePrestamosSucursalLoad();Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-prestamo').setValue("");Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-sucursal').setValue("");Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-concepto').setValue("");Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-saldo').setValue("");Ext.getCmp('Operaciones-abonarPrestamoEfectivoSucursal-monto').setValue("");},failure:function(response){POS.error(response);}});};POS.Apps.push(new Aplicacion.Operaciones());Aplicacion.Personal=function(){return this._init();}
Aplicacion.Personal.prototype._init=function(){if(DEBUG){console.log("Personal: construyendo");}
this.listaDePersonalPanelCreator();this.nuevoEmpleadoPanelCreator();this.listaDePersonalLoad();this.detallesDeEmpleadoPanelCreator();this.nuevoEmpleadoGargarTipos();Aplicacion.Personal.currentInstance=this;return this;};Aplicacion.Personal.prototype.getConfig=function(){return{text:'Personal',cls:'launchscreen',items:[{text:'Lista de personal',card:this.listaDePersonalPanel,leaf:true},{text:'Nuevo empleado',card:this.nuevoEmpleadoPanel,leaf:true}]};};Aplicacion.Personal.prototype.listaDePersonal={lista:[],lastUpdate:null};Ext.regModel('listaDePersonalModel',{fields:[{name:'nombre',type:'string'}]});Aplicacion.Personal.prototype.listaDePersonalStore=new Ext.data.Store({model:'listaDePersonalModel',sorters:'nombre',getGroupString:function(record){return record.get('nombre')[0];}});Aplicacion.Personal.prototype.listaDePersonalLoad=function()
{if(DEBUG){console.log("Cargando la lista de personal");}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:501},success:function(response,opts){try{personal=Ext.util.JSON.decode(response.responseText);}catch(e){POS.error(e);}
if(!personal.success){return;}
this.listaDePersonal.lista=personal.empleados;this.listaDePersonal.lastUpdate=Math.round(new Date().getTime()/1000.0);this.listaDePersonalStore.loadData(personal.empleados);},failure:function(response){POS.error(response);}});};Aplicacion.Personal.prototype.listaDePersonalPanel=null;Aplicacion.Personal.prototype.listaDePersonalPanelCreator=function(){this.listaDePersonalPanel=new Ext.Panel({layout:Ext.is.Phone?'fit':{type:'vbox',align:'center',pack:'center'},items:[{width:'100%',height:'100%',xtype:'list',store:this.listaDePersonalStore,itemTpl:'<div class="listaDePersonal"><strong>{nombre}</strong></div>',grouped:true,indexBar:true,listeners:{"selectionchange":function(view,nodos,c){if(nodos.length>0){Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanelShow(nodos[0]);}
view.deselectAll();}}}]});};Aplicacion.Personal.prototype.detallesDeEmpleadoPanelShow=function(e)
{if(DEBUG){console.log("Mostrando detalles de empleado",e);}
this.detallesDeEmpleadoPanelUpdater(e);sink.Main.ui.setActiveItem(this.detallesDeEmpleadoPanel,'slide');}
Aplicacion.Personal.prototype.detallesDeEmpleadoPanelUpdater=function(empleado)
{Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).loadRecord(empleado);};Aplicacion.Personal.prototype.editarDetallesEmpleadoDespedirBoton=function()
{Ext.Msg.confirm("Prescindir","&iquest; Esta seguro que desea despedir a este empleado ? ",function(a){if(a=="yes"){v=Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getValues();v.activo=0;Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:503,activo:v.activo,id_empleado:v.id_usuario},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){Ext.getBody().mask('Error Interno','',false);return POS.error(e);}
if(!r.success){return POS.error(r);}
Aplicacion.Personal.currentInstance.listaDePersonalLoad();setTimeout("sink.Main.ui.setActiveItem( Aplicacion.Personal.currentInstance.listaDePersonalPanel , 'fade');",500);},failure:function(response){POS.error(response);}});}});};Aplicacion.Personal.prototype.editarDetallesEmpleadoBoton=function()
{Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getComponent(0).setInstructions("Haga los cambios pertinentes.");Ext.getCmp("Personal-DetallesEmpleadoID").hide(Ext.anims.slide);Ext.getCmp("Personal-DetallesEmpleadoModificar").hide(Ext.anims.fade);Ext.getCmp("Personal-DetallesEmpleadoPuesto").hide(Ext.anims.slide);Ext.getCmp("Personal-DetallesEmpleadoDespedir").hide();Ext.getCmp("Personal-DetallesEmpleadoGuardar").show();Ext.getCmp("Personal-DetallesEmpleadoCancelar").show();Ext.getCmp("Personal-DetallesEmpleadoSalario").hide();Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).enable();};Aplicacion.Personal.prototype.editarDetallesEmpleadoCancelarBoton=function(override)
{if(override)
Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getComponent(0).setInstructions("");Ext.getCmp("Personal-DetallesEmpleadoID").show(Ext.anims.slide);Ext.getCmp("Personal-DetallesEmpleadoModificar").show(Ext.anims.fade);Ext.getCmp("Personal-DetallesEmpleadoPuesto").show(Ext.anims.slide);Ext.getCmp("Personal-DetallesEmpleadoDespedir").show();Ext.getCmp("Personal-DetallesEmpleadoGuardar").hide();Ext.getCmp("Personal-DetallesEmpleadoCancelar").hide();Ext.getCmp("Personal-DetallesEmpleadoSalario").hide();Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).disable();};Aplicacion.Personal.prototype.editarDetallesEmpleadoGuardarBoton=function()
{Ext.getBody().mask('Modificando datos ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:502,data:Ext.util.JSON.encode(Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getValues())},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){Ext.getBody().mask('Error Interno','',false);return POS.error(e);}
Ext.getBody().unmask();if(!r.success){Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getComponent(0).setInstructions(r.reason);return;}
Aplicacion.Personal.currentInstance.editarDetallesEmpleadoCancelarBoton(true);Aplicacion.Personal.currentInstance.listaDePersonalLoad();Aplicacion.Personal.currentInstance.detallesDeEmpleadoPanel.getComponent(0).getComponent(0).setInstructions("Los cambios se han hecho satisfactoriamente !");Ext.getCmp("Personal-DetallesEmpleadoSalario").hide();},failure:function(response){POS.error(response);}});};Aplicacion.Personal.prototype.detallesDeEmpleadoPanel=null;Aplicacion.Personal.prototype.detallesDeEmpleadoPanelCreator=function(){if(DEBUG){console.log("creando panel de detalles de empleado por primera vez");}
this.detallesDeEmpleadoPanel=new Ext.Panel({scroll:"vertical",items:[new Ext.form.FormPanel({title:'Detalles de Empleado',listeners:{"beforeshow":function(){Ext.getCmp("Personal-DetallesEmpleadoTipoSelector").setOptions(Aplicacion.Personal.currentInstance.nuevoEmpleadoTipos);}},items:[{xtype:'fieldset',title:'Detalles del nuevo empleado',instructions:'',defaults:{disabled:true},items:[new Ext.form.Text({name:'nombre',label:'Nombre'}),new Ext.form.Text({name:'activo',label:"activo",hidden:true}),new Ext.form.Text({name:'id_sucursal',label:'Sucursal',hidden:true}),new Ext.form.Text({name:'finger_token',label:'Token',hidden:true}),new Ext.form.Text({name:'tipo',label:'tipo',hidden:true}),new Ext.form.Text({id:"Personal-DetallesEmpleadoID",name:'id_usuario',label:'ID'}),new Ext.form.Text({id:"Personal-DetallesEmpleadoPuesto",name:'puesto',label:'Puesto'}),new Ext.form.Text({name:'RFC',label:'RFC'}),new Ext.form.Text({name:'direccion',label:'Direccion'}),new Ext.form.Text({name:'telefono',label:'Telefono'}),new Ext.form.Text({id:"Personal-DetallesEmpleadoSalario",name:'salario',hidden:true,label:'Salario'})]}]}),new Ext.Button({id:"Personal-DetallesEmpleadoModificar",ui:'drastic',text:'Modificar Detalles',margin:15,handler:this.editarDetallesEmpleadoBoton}),new Ext.Button({id:"Personal-DetallesEmpleadoGuardar",ui:'confirm',text:'Guardar',margin:15,handler:this.editarDetallesEmpleadoGuardarBoton,hidden:true}),new Ext.Button({id:"Personal-DetallesEmpleadoCancelar",ui:'decline',text:'Cancelar',margin:15,handler:this.editarDetallesEmpleadoCancelarBoton,hidden:true}),new Ext.Button({id:"Personal-DetallesEmpleadoDespedir",ui:'decline',text:'Despedir',margin:15,handler:this.editarDetallesEmpleadoDespedirBoton})]});};Aplicacion.Personal.prototype.nuevoEmpleadoPanel=null;Aplicacion.Personal.prototype.crearEmpleadoValidar=function()
{v=Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getValues();if(isNaN(v.grupo)||v.grupo.length==0){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("Seleccione el rol de este nuevo empleado.");return false;}
if(v.nombre.length<5){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("El nombre es muy corto.");return false;}
if(v.RFC.length<10){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("El RFC es muy corto.");return false;}
if(v.grupo==3){if(v.contrasena.length<5){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("La contrase&ntilde;a debe ser mayor a 5 caracteres.");return false;}
if(v.contrasena!=v.contrasena2){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("Las contrase&ntilde;as no coinciden.");return false;}}
if(isNaN(v.salario)){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("El salario debe ser un numero.");return false;}
if(v.salario<0){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("No puede asingar un salario negativo.");return false;}
Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("");return true;}
Aplicacion.Personal.prototype.crearEmpleadoBoton=function()
{if(DEBUG){console.log("Creando empleado");}
if(!Aplicacion.Personal.currentInstance.crearEmpleadoValidar()){return;}
if(DEBUG){console.log("Enviando peticion");}
Ext.getBody().mask('Creando empleado ...','x-mask-loading',true);v=Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getValues();v.contrasena=hex_md5(v.contrasena);v.contrasena2=hex_md5(v.contrasena2);json=Ext.util.JSON.encode(v);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:500,data:json},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
Ext.getBody().unmask();if(!r.success){Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions(r.reason);Ext.Msg.alert("Nueva contratacion",r.reason);return;}
Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.reset();Aplicacion.Personal.currentInstance.listaDePersonalLoad();Ext.Msg.alert("Nueva contratacion","El nuevo usuario se ha creado satisfactoriamente con el ID <b>"+r.id_usuario+"</b>");Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.getComponent(0).setInstructions("El nuevo empleado se ha creado satisfactoriamente con el ID <b>"+r.id_usuario+"</b>.");sink.Main.ui.setActiveItem(this.listaDePersonalPanel,'slide');},failure:function(response){POS.error(response);}});}
Aplicacion.Personal.prototype.reincorporarEmpleado=function(v,id_usuario)
{Ext.Msg.confirm("Nuevo Empleado","&iquest; Ya se tiene registro de este empleado, desea reincorporarlo nuevamente? ",function(a){if(a=="yes"){v.id_usuario=id_usuario;v.activo=1;Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:502,data:Ext.util.JSON.encode(v)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){Ext.getBody().mask('Error Interno','',false);return POS.error(e);}
if(!r.success){return POS.error(r);}
Aplicacion.Personal.currentInstance.nuevoEmpleadoPanel.reset();Aplicacion.Personal.currentInstance.listaDePersonalLoad();setTimeout("sink.Main.ui.setActiveItem( Aplicacion.Personal.currentInstance.listaDePersonalPanel , 'fade');",500);},failure:function(response){POS.error(response);}});}});};Aplicacion.Personal.prototype.nuevoEmpleadoTipos=[];Aplicacion.Personal.prototype.nuevoEmpleadoGargarTipos=function()
{Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:504},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(!r.success){return;}
Aplicacion.Personal.currentInstance.nuevoEmpleadoTipos=r.datos;},failure:function(response){POS.error(response);}});};Aplicacion.Personal.prototype.nuevoEmpleadoCambiarTipo=function(a,v)
{if(v==3){Ext.getCmp("Personal-NuevoEmpleadoPass").show(Ext.anims.slide);Ext.getCmp("Personal-NuevoEmpleadoPass2").show(Ext.anims.slide);}else{Ext.getCmp("Personal-NuevoEmpleadoPass").hide(Ext.anims.slide);Ext.getCmp("Personal-NuevoEmpleadoPass2").hide(Ext.anims.slide);}};Aplicacion.Personal.prototype.nuevoEmpleadoPanelCreator=function(){if(DEBUG){console.log("creando panel de nuevo cliente");}
this.nuevoEmpleadoPanel=new Ext.form.FormPanel({listeners:{"show":function(){Ext.getCmp("Personal-NuevoEmpleadoTipoSelector").setOptions(Aplicacion.Personal.currentInstance.nuevoEmpleadoTipos);}},items:[{xtype:'fieldset',title:'Contratacion de un nuevo empleado',instructions:'Introdusca los detalles del nuevo empleado.',items:[{id:"Personal-NuevoEmpleadoTipoSelector",xtype:'selectfield',name:'grupo',label:"Tipo",options:[{text:"Seleccione el nuevo rol que cumplira este empleado",value:null}],listeners:{"change":function(a,b){Aplicacion.Personal.currentInstance.nuevoEmpleadoCambiarTipo(a,b);}}},new Ext.form.Text({name:'nombre',label:'Nombre',listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({name:'RFC',label:'RFC',listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Password({id:"Personal-NuevoEmpleadoPass",name:'contrasena',label:'Contrase&ntilde;a',hidden:true,listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Password({id:"Personal-NuevoEmpleadoPass2",name:'contrasena2',label:'Repetir contrase&ntilde;a',hidden:true,listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({name:'salario',label:'Salario',listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({name:'direccion',label:'direccion',listeners:{'focus':function(){kconf={type:'complete',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({name:'telefono',label:'telefono',listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({id:'Personal-CrearEmpleado',ui:'action',text:'Contratar',margin:15,handler:this.crearEmpleadoBoton,disabled:false}),]});};POS.Apps.push(new Aplicacion.Personal());Aplicacion.Proveedores=function(){var listaDeProveedores;Aplicacion.Proveedores.ci=this;this.cards={lista:null,detalles:null,carrito:null,nuevo:null};this.popups={listaDeProductos:null};var cargarListaDeProveedores=function(showPanel){Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:900},success:function(response,opts){var proveedores;try{proveedores=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(DEBUG){console.log("Lista de proveedores ha regresado.");}
listaDeProveedores=proveedores.payload;if(showPanel){sink.Main.ui.setActiveItem(Aplicacion.Proveedores.ci.cards.lista,'slide');}},failure:function(response){POS.error(response);}});};this.mostrarDetalles=function(id_proveedor){if(DEBUG){console.log("mostrando los detalles del proveeedor ",id_proveedor);}
if(id_proveedor==-1){sink.Main.ui.setActiveItem(Aplicacion.Inventario.currentInstance.surtirWizardPanel,'slide');return;}
thiz=Aplicacion.Proveedores.ci;var tarjeta=thiz.cards.detalles;var a;for(a=0;a<listaDeProveedores.length;a++){if(listaDeProveedores[a].id_proveedor===id_proveedor){break;}}
if(a===listaDeProveedores.length){return;}
var proveedor=listaDeProveedores[a];tarjeta.setValues({nombre:proveedor.nombre,direccion:proveedor.direccion,telefono:proveedor.telefono});Aplicacion.Proveedores.ci.currentProveedor=id_proveedor;sink.Main.ui.setActiveItem(tarjeta,'slide');};this.currentProveedor=null;this.addToCart=function(item){if(DEBUG){console.log("agregnaod item",item.data);}
for(var i=carritoItems.length-1;i>=0;i--){if(carritoItems[i].get("productoID")==item.get("productoID")){if(DEBUG){console.log("este producto ya existe en el carrito para surtir");}
refreshSurtir();return;}}
item.cantidad=1;carritoItems.push(item);if(DEBUG){console.log("Agregando nuevo",item);}
refreshSurtir();};var carritoItems=[];this.cancelarPedido=function(){carritoItems=[];refreshSurtir();};this.quitarDelCarrito=function(id_producto){if(DEBUG){console.log("Removiendo del carrito.");}
for(var i=carritoItems.length-1;i>=0;i--){if(carritoItems[i].get("productoID")==id_producto){carritoItems.splice(i,1);break;}}
refreshSurtir();};this.carritoCambiarCantidad=function(id,qty,forceNewValue){for(var i=carritoItems.length-1;i>=0;i--){if(carritoItems[i].get("productoID")==id){if(forceNewValue){carritoItems[i].cantidad=qty;}else{carritoItems[i].cantidad+=qty;}
if(carritoItems[i].cantidad<=0){carritoItems[i].cantidad=1;}
refreshSurtir();break;}}};var refreshSurtir=function(){if(DEBUG){console.log("Refrescanco el carrito para surtir de proveedor externo...");}
if(carritoItems.length>0){Ext.getCmp("Proveedores-confirmarPedido").show(Ext.anims.slide);Ext.getCmp("Proveedores-cancelarPedido").show(Ext.anims.slide);}else{Ext.getCmp("Proveedores-confirmarPedido").hide(Ext.anims.slide);Ext.getCmp("Proveedores-cancelarPedido").hide(Ext.anims.slide);}
var html="<table border=0>";html+="<tr class='top'>";html+="   <td>Descripcion</td>";html+="   <td>&nbsp;</td>";html+="   <td colspan=4 align = center>Cantidad</td>";html+="   <td >Costo</td>";html+="   <td>Sub Total</td>";html+="</tr>";for(var i=0;i<carritoItems.length;i++){if(carritoItems[i].cantidad===null){carritoItems[i].cantidad=1;}
if(i==carritoItems.length-1)
{html+="<tr class='last'>";}
else
{html+="<tr >";}
var m;switch(carritoItems[i].get("medida")){case"kilogramo":m="kgs";break;case"pieza":m="pzas";break;case"litro":m="lts";break;}
html+="   <td style='width: 17%;' ><b>"+carritoItems[i].get("productoID")+"</b> &nbsp; "+carritoItems[i].get("descripcion")+"</td>";html+="   <td style='width: 12%;'> <span class = 'boton' onClick = 'Aplicacion.Proveedores.ci.quitarDelCarrito("+carritoItems[i].get("productoID")+")'><img src='../media/icons/close_16.png'></span></span> </td>";html+="   <td style='width: 8.1%;'> <span class='boton' onClick=\"Aplicacion.Proveedores.ci.carritoCambiarCantidad('"+carritoItems[i].get("productoID")+"', -1, false)\">&nbsp;-&nbsp;<img src='../media/icons/arrow_down_16.png'></span></td>";html+="   <td style='width: 8.1%;' > <div id='Proveedores-carritoCantidad"+carritoItems[i].get("productoID")+"'></div> </td>";html+="   <td style='width: 6%;'>"+m+"</td>";html+="   <td style='width: 8.1%;'> <span class='boton' onClick=\"Aplicacion.Proveedores.ci.carritoCambiarCantidad('"+carritoItems[i].get("productoID")+"', 1, false)\"><img src='../media/icons/arrow_up_16.png'>&nbsp;+&nbsp;</span></td>";html+="   <td style='width: 10.4%;'> <div id='Proveedores-carritoCosto"+carritoItems[i].get("productoID")+"'> "+POS.currencyFormat(carritoItems[i].get("precioIntersucursal"))+" </div></td>";html+="   <td style='width: 12.3%;'>"+POS.currencyFormat(carritoItems[i].cantidad*carritoItems[i].get("precioVenta"))+"</td>";html+="</tr>";}
html+="</table>";Ext.getCmp("Proveedores-surtirTabla").update(html);for(i=0;i<carritoItems.length;i++){a=new Ext.form.Text({renderTo:"Proveedores-carritoCantidad"+carritoItems[i].get("productoID"),id:"Proveedores-carritoCantidad"+carritoItems[i].get("productoID")+"Text",value:carritoItems[i].cantidad,prodID:carritoItems[i].get("productoID"),placeHolder:"Cantidad",listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:function(campo){for(i=0;i<carritoItems.length;i++){if(carritoItems[i].get("productoID")==campo.prodID){carritoItems[i].cantidad=parseFloat(campo.getValue());if(isNaN(campo.getValue())||campo.getValue()<=0)
{carritoItems[i].cantidad=1;}
break;}}
refreshSurtir();}};POS.Keyboard.Keyboard(this,kconf);}}});}};if(DEBUG){console.log("Construyendo aplicacion de proveedores");}
cargarListaDeProveedores();this.cards.detalles=new Ext.form.FormPanel({dockedItems:[{dock:'bottom',xtype:'toolbar',items:[{text:'Regresar a lista de proveedores',ui:'back',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Proveedores.ci.cards.lista,'slide');}},{xtype:'spacer'},{text:'Surtirse de este proveedor',ui:'action',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Proveedores.ci.cards.carrito,'slide');}}]}],items:[{xtype:'fieldset',items:[new Ext.form.Text({name:'nombre',label:'Nombre'}),new Ext.form.Text({name:'direccion',label:'Direccion'}),new Ext.form.Text({name:'telefono',label:'Telefono'}),]}]});this.cards.lista=new Ext.Panel({dockedItems:[{dock:'bottom',xtype:'toolbar',items:[{text:'Agregar Nuevo Proveedor',ui:'action',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Proveedores.ci.cards.nuevo,'slide');}}]}],layout:'fit',items:[{html:"<div style='height: 100%;' id='MosaicoProveedores'></div>"}],listeners:{"show":function(){if(DEBUG){console.log("Creando mosaico para proveedores",this);}
items=[];items.push({title:"Centro de distribucion",id:-1,image:'../media/TruckYellow128.png'});if(DEBUG){console.log("Hay "+listaDeProveedores.length+" proveedores.");}
for(a=0;a<listaDeProveedores.length;a++){items.push({title:listaDeProveedores[a].nombre,id:listaDeProveedores[a].id_proveedor,image:'../media/LorryGreen128.png'});};new Mosaico({renderTo:'MosaicoProveedores',callBack:Aplicacion.Proveedores.ci.mostrarDetalles,items:items});}}});this.cards.nuevo=new Ext.form.FormPanel({dockedItems:[{dock:'bottom',xtype:'toolbar',items:[{text:'Regresar',ui:'back',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Proveedores.ci.cards.lista,'slide');}}]}],items:[{xtype:'fieldset',title:'Detalles del nuevo proveedor',instructions:'Ingrese los detalles del nuevo proveedor.',items:[new Ext.form.Text({id:'Proveedores-nombre',label:'Nombre',name:'nombre',required:true,listeners:{'focus':function(){kconf={type:'alfa',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Proveedores-rfc',name:'rfc',label:'RFC',required:true,listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Proveedores-direccion',label:'Direccion',name:'direccion',required:true,listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Proveedores-email',label:'Email',name:'e_mail',listeners:{'focus':function(){kconf={type:'alfanum',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Proveedores-telefono',label:'Telefono',name:'telefono',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Select({name:"tipo_proveedor",label:"Tipo",value:"sucursal",options:[{text:"Sucursal",value:"sucursal"},{text:"Ambos",value:"ambos"}]})]},new Ext.Button({ui:'action',text:'Registrar Proveedor',margin:5,handler:function(){Aplicacion.Proveedores.ci.registrarNuevoProveedorValidator();}})]});this.registrarNuevoProveedorValidator=function(){var values=Aplicacion.Proveedores.ci.cards.nuevo.getValues();if(values.nombre.length<10){Ext.Anim.run(Ext.getCmp('Proveedores-nombre'),'fade',{duration:250,out:true,autoClear:true});return;}
if(values.rfc.length<10){Ext.Anim.run(Ext.getCmp('Proveedores-rfc'),'fade',{duration:250,out:true,autoClear:true});return;}
if(values.direccion.length<10){Ext.Anim.run(Ext.getCmp('Proveedores-direccion'),'fade',{duration:250,out:true,autoClear:true});return;}
this.registrarNuevoProveedor(values);};this.registrarNuevoProveedor=function(values){Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:901,data:Ext.util.JSON.encode(values)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){POS.error(e);}
if(!r.success){Ext.Msg.alert("Nuevo Proveedor",r.reason);return;}
Ext.Msg.alert("Nuevo Proveedor","Proveedor Registrado Correctramente");cargarListaDeProveedores(true);},failure:function(response){return POS.error(response);}});};this.cards.carrito=new Ext.Panel({dockedItems:new Ext.Toolbar({ui:'dark',dock:'bottom',items:[{text:'Agregar  producto',ui:'normal',handler:function(t){Aplicacion.Proveedores.ci.popups.listaDeProductos.showBy(this);}},{xtype:'spacer'},{text:'Cancelar pedido',ui:'normal',id:'Proveedores-cancelarPedido',handler:function(t){Aplicacion.Proveedores.ci.cancelarPedido();}},{text:'Confirmar pedido',ui:'action',hidden:true,id:'Proveedores-confirmarPedido',handler:function(t){alert("ok");Aplicacion.Proveedores.ci.confirmar();}}]}),html:"",id:"Proveedores-surtirTabla",cls:"Tabla"});this.popups.listaDeProductos=new Ext.Panel({floating:true,ui:"dark",modal:false,scroll:false,width:300,height:500,showAnimation:Ext.anims.fade,hideOnMaskTap:true,bodyPadding:0,bodyMargin:0,styleHtmlContent:false,items:[{multiSelect:true,xtype:'list',ui:'dark',store:Aplicacion.Inventario.currentInstance.inventarioListaStore,itemTpl:'<div class=""><b>{productoID}</b> {descripcion}</div>',indexBar:false,listeners:{"selectionchange":function(view,nodos,c){if(nodos.length>0){Aplicacion.Proveedores.ci.popups.listaDeProductos.hide()
Aplicacion.Proveedores.ci.addToCart(nodos[0]);}
view.deselectAll();}}}]});this.confirmar=function(){var carrito={id_proveedor:Aplicacion.Proveedores.ci.currentProveedor,productos:[]};for(var i=0;i<carritoItems.length;i++){carrito.productos.push({id_producto:carritoItems[i].get("productoID"),cantidad:carritoItems[i].cantidad});}
if(DEBUG){console.log("El JSON de productos a comprar es : ",carrito);}
Ext.getBody().mask('Registrando Compra...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:302,data:Ext.util.JSON.encode(data)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){POS.error(e);}
Ext.getBody().unmask();if(!r.success){return;}}});};};Aplicacion.Proveedores.prototype.getConfig=function(){return{text:'Proveedores',card:this.cards.lista,leaf:true,items:[{text:'Lista de proveedores',card:this.cards.lista,leaf:true},{text:'Comprar a proveedor',card:null,leaf:true}]};};POS.Apps.push(new Aplicacion.Proveedores());