#!/bin/bash

cd ..

g++ -I /usr/local/include/mysql++/ -I /usr/include/mysql/ -I /usr/local/include/hiredis -L/usr/local/libhiredis -L/usr/lib/mysql -lmysqlclient -lmysqlpp -lhiredis -o chat.bin src/chat.cpp 



#g++ -I /usr/local/include/mysql++/ -I /usr/include/mysql/ -L/usr/lib/mysql -lmysqlclient -lmysqlpp -o chat.bin src/chat.cpp
	
