
Aplicacion.Autorizaciones=function(){return this._init();}
Aplicacion.Autorizaciones.prototype._init=function(){if(DEBUG){console.log("Autorizaciones: construyendo");}
Aplicacion.Autorizaciones.currentInstance=this;this.nueva.createPanels();this.listaDeAutorizacionesPanelCreator();this.listaDeAutorizacionesLoad();this.finishedPanelCreator()
return this;};Aplicacion.Autorizaciones.prototype.getConfig=function(){return{text:'Autorizaciones',cls:'launchscreen',card:Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel,items:[{text:'Nueva Autorizacion',items:[{text:'Limite de Credito',card:Aplicacion.Autorizaciones.currentInstance.nueva.creditoPanel,leaf:true},{text:'Venta Preferencial',card:Aplicacion.Autorizaciones.currentInstance.nueva.ventaPreferencialPanel,leaf:true},{text:'Devoluciones',card:Aplicacion.Autorizaciones.currentInstance.nueva.devolucionesPanel,leaf:true}]},{text:'Lista de Autorizaciones',card:Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel,leaf:true}]};};Aplicacion.Autorizaciones.prototype.nueva={};Aplicacion.Autorizaciones.prototype.nueva.createPanels=function()
{this.devolucionesPanelCreator();this.creditoPanelCreator();this.mermaPanelCreator();this.ventaPreferencialPanelCreator();};Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanel=null;Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanelCliente=null;Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanelClienteCreator=function(cliente){if(DEBUG){console.log('cliente ----------->',cliente);}
this.ventaPreferencialPanelCliente=new Ext.form.FormPanel({title:'Solicitud de Venta Preferencial',dockedItems:[new Ext.Toolbar({ui:'light',dock:'bottom',items:[{text:'Regresar',ui:'back',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Autorizaciones.currentInstance.nueva.ventaPreferencialPanel,'slide');}}]})],items:[{xtype:'fieldset',title:'Solicitud de Venta Preferencial',items:[new Ext.form.Text({id:'Autorizaciones-ventaPreferencial-cliente',label:'Razon Social',value:cliente.razon_social}),new Ext.form.Text({label:'RFC',value:cliente.rfc}),new Ext.form.Text({label:'Limite de Credito',value:cliente.limite_credito}),new Ext.form.Text({label:'Credito Restante',value:cliente.credito_restante}),new Ext.form.Hidden({id:'Autorizaciones-ventaPreferencial-clienteID',value:cliente.id_cliente})]},{xtype:'spacer'},new Ext.Button({id:'Autorizaciones-ventaPreferencial-action',ui:'action',text:'Solicitar Autorización',handler:this.ventaPreferencialPanelValidator})]});sink.Main.ui.setActiveItem(this.ventaPreferencialPanelCliente,'slide');}
Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanelCreator=function()
{this.ventaPreferencialPanel=new Ext.Panel({layout:'fit',items:[{xtype:'list',store:Aplicacion.Clientes?Aplicacion.Clientes.currentInstance.listaDeClientesStore:null,itemTpl:'<div class="listaDeClientesCliente"><strong>{razon_social}</strong> {rfc}</div>',grouped:true,indexBar:true,listeners:{"selectionchange":function(view,nodos,c){if(nodos.length>0){console.log(nodos[0].data)
if(nodos[0].get("id_cliente")<=0){Ext.Msg.alert("Autorizaciones","No puede realizar una solicitud de venta preferencial para una sucursal.");}
else{Aplicacion.Autorizaciones.currentInstance.nueva.ventaPreferencialPanelClienteCreator(nodos[0].data);}}
view.deselectAll();}}}]});};Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanelShow=function(cliente)
{if(!this.ventaPreferencialPanel){this.ventaPreferencialPanelCreator();}
sink.Main.ui.setActiveItem(this.ventaPreferencialPanel,'slide');};Aplicacion.Autorizaciones.prototype.nueva.ventaPreferencialPanelValidator=function(){var cliente={id_cliente:null,nombre:null};cliente.id_cliente=Ext.getCmp('Autorizaciones-ventaPreferencial-clienteID').getValue();cliente.nombre=Ext.getCmp('Autorizaciones-ventaPreferencial-cliente').getValue();if(cliente.id_cliente=="")
{Ext.Anim.run(Ext.getCmp('Autorizaciones-ventaPreferencial-cliente'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Autorizaciones.currentInstance.nueva.autorizacionVentaPreferencial(cliente);};Aplicacion.Autorizaciones.prototype.nueva.autorizacionVentaPreferencial=function(cliente){Ext.getBody().mask('Enviando autorizacion de venta preferencial','x-mask-loading',true);if(DEBUG){console.log("Enviando autorizacion de venta preferencial");}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:204,id_cliente:cliente.id_cliente,nombre:cliente.nombre},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();if(r.success==true)
{Ext.Msg.alert("Autorizacion","Se ha enviado su autorización");sink.Main.ui.setActiveItem(Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel,'fade');Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesLoad();}
else
{Ext.Msg.alert("Autorizacion","Error: "+r.success);}},failure:function(response){POS.error(response);}});};Aplicacion.Autorizaciones.prototype.nueva.creditoModificarPanel=null;Aplicacion.Autorizaciones.prototype.nueva.creditoModificarPanelShow=function(cliente)
{if(!this.creditoModificarPanel){this.creditoModificarPanelCreator();}
Ext.getCmp("Autorizaciones-CreditoIdCliente").setValue(cliente.data.id_cliente);Ext.getCmp("Autorizaciones-CreditoCliente").setValue(cliente.data.razon_social);Ext.getCmp("Autorizaciones-CreditoActual").setValue(POS.currencyFormat(cliente.data.limite_credito));Ext.getCmp("Autorizaciones-CreditoUsado").setValue(POS.currencyFormat(cliente.data.limite_credito-cliente.credito_restante));sink.Main.ui.setActiveItem(this.creditoModificarPanel,'slide');};Aplicacion.Autorizaciones.prototype.nueva.nuevoCreditoModificar=function(data){Ext.getBody().mask('Enviando autorizacion de credito','x-mask-loading',true);if(DEBUG){console.log("Enviando autorizacion de credito extendido",data);}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:202,id_cliente:data.id_cliente,cantidad:data.limite,nombre:data.nombre},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();Aplicacion.Autorizaciones.currentInstance.nueva.creditoModificarPanel.reset();if(r.success==true)
{Ext.Msg.alert("Autorizacion","Se ha enviado su autorización");Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesLoad();}
else
{Ext.Msg.alert("Autorizacion","Error: "+r.success);}},failure:function(response){POS.error(response);}});};Aplicacion.Autorizaciones.prototype.nueva.nuevoCreditoModificarValidator=function(){var values=Aplicacion.Autorizaciones.currentInstance.nueva.creditoModificarPanel.getValues();if(!(values.limite&&/^-?\d+(\.\d+)?$/.test(values.limite+''))){Ext.Anim.run(Ext.getCmp('Autorizaciones-CreditoNuevo'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Autorizaciones.currentInstance.nueva.nuevoCreditoModificar(values);};Aplicacion.Autorizaciones.prototype.nueva.creditoModificarPanelCreator=function()
{this.creditoModificarPanel=new Ext.form.FormPanel({items:[{xtype:'fieldset',title:'Solicitud de limite de credito extendido',instructions:'Ingrese el nuevo limite de credito para este cliente.',items:[new Ext.form.Hidden({id:'Autorizaciones-CreditoIdCliente',name:'id_cliente'}),new Ext.form.Text({id:'Autorizaciones-CreditoCliente',name:'nombre',label:'Cliente',disabled:true}),new Ext.form.Text({id:'Autorizaciones-CreditoActual',label:'Actual',disabled:true}),new Ext.form.Text({id:'Autorizaciones-CreditoUsado',label:'Usado',disabled:true}),new Ext.form.Text({id:'Autorizaciones-CreditoNuevo',label:'Nuevo limite',name:'limite',required:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar'};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Pedir autorizacion',margin:5,handler:this.nuevoCreditoModificarValidator})]});};Aplicacion.Autorizaciones.prototype.nueva.creditoPanel=null;Aplicacion.Autorizaciones.prototype.nueva.creditoPanelCreator=function()
{this.creditoPanel=new Ext.form.FormPanel({items:[{xtype:'fieldset',title:'Limite de credito extendido',instructions:'Seleccione al cliente al que desea extenerle el credito',items:[{width:'100%',height:600,padding:2,xtype:'list',store:Aplicacion.Clientes.currentInstance.listaDeClientesStore,itemTpl:'<div class="listaDeClientesCliente"><strong>{razon_social}</strong> {rfc}</div>',grouped:true,indexBar:true,listeners:{"selectionchange":function(view,nodos,c){if(nodos.length>0){if(nodos[0].get("id_cliente")<=0){Ext.Msg.alert("Autorizaciones","No puede realizar una solicitud de limite de credito extendido para una sucursal.");}
else{Aplicacion.Autorizaciones.currentInstance.nueva.creditoModificarPanelShow(nodos[0]);}}
view.deselectAll();}}}]}]});};Aplicacion.Autorizaciones.prototype.solicitudAutorizacionMerma=function(values){Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:205,data:Ext.util.JSON.encode(values)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Aplicacion.Autorizaciones.currentInstance.panelSolicitudMerma.hide('pop');if(!r.success)
{Ext.Msg.alert("Autorizaciones","Error: "+r.reason);}
Ext.Msg.alert("Autorizaciones","Solicitud enviada con exito.");Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesLoad();},failure:function(response){POS.error(response);}});}
Aplicacion.Autorizaciones.prototype.solicitarMermaCompraPanelValidator=function()
{values=Aplicacion.Autorizaciones.currentInstance.solicitarMermaCompraPanel.getValues();if(!(values.cantidad&&/^\d+$/.test(values.cantidad+''))){Ext.Anim.run(Ext.getCmp('Autorizacion-MermaCompraPanel-cantidad'),'fade',{duration:250,out:true,autoClear:true});return;}
if(values.cantidadOriginal<values.cantidad){Ext.Anim.run(Ext.getCmp('Autorizacion-MermaCompraPanel-cantidad'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Autorizaciones.currentInstance.solicitudAutorizacionMerma(values);};Aplicacion.Autorizaciones.prototype.solicitarMermaCompra=function(id_compra,id_producto,cantidadOriginal)
{this.solicitarMermaCompraPanel=new Ext.form.FormPanel({scroll:'none',items:[{xtype:'fieldset',title:'Reportar merma en compra',instructions:'Ingrese la cantidad de Merma.',items:[new Ext.form.Text({name:'id_compra',label:'ID Compra',disabled:true,value:id_compra}),new Ext.form.Text({name:'id_producto',label:'ID Producto',disabled:true,value:id_producto}),new Ext.form.Text({name:'cantidadOriginal',disabled:true,label:'Cantidad comprada',value:cantidadOriginal}),new Ext.form.Text({id:'Autorizacion-MermaCompraPanel-cantidad',name:'cantidad',label:'Cantidad reportada',listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:Aplicacion.Efectivo.currentInstance.nuevoGastoValidator};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Enviar Solicitud',margin:15,handler:this.solicitarMermaCompraPanelValidator})]});this.panelSolicitudMerma=new Ext.Panel({floating:true,modal:true,centered:true,height:390,width:680,scroll:'none',items:[this.solicitarMermaCompraPanel]});this.panelSolicitudMerma.show('pop');};Aplicacion.Autorizaciones.prototype.listaDetalleCompra=function(id_compra)
{Ext.getBody().mask('Obteniendo lista de compras ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:403,id_compra:id_compra},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!r.success)
{Ext.getCmp('MermaHtmlPanel').update("No se tiene registro de esa compra");Ext.getBody().unmask();}
var html="";if(r.datos.num_compras==0)
{Ext.getCmp('MermaHtmlPanel').update("No se tiene registro del detalle de esa compra");Ext.getBody().unmask();return;}
if(Aplicacion.Autorizaciones.currentInstance.nueva.numeroCompra!=r.datos.id_compra)
{Aplicacion.Autorizaciones.currentInstance.nueva.numeroCompra=r.datos.id_compra;html+="<table border = 0>";html+="   <tr class = 'top'>";html+="       <td>id_compra</td>";html+="       <td>id_producto</td>";html+="       <td>descripcion</td>";html+="       <td>cantidad</td>";html+="       <td>precio</td>";html+="   </tr>";for(var i=0;i<r.datos.num_compras;i++)
{html+="<tr class = 'Autorizaciones-row' onClick = ' Aplicacion.Autorizaciones.currentInstance.solicitarMermaCompra("+r.datos.id_compra+","+r.datos.compras[i].id_producto+", "+r.datos.compras[i].cantidad+") ' >";html+="   <td>"+r.datos.id_compra+"</td>";html+="   <td>"+r.datos.compras[i].id_producto+"</td>";html+="   <td>"+r.datos.compras[i].descripcion+"</td>";html+="   <td>"+r.datos.compras[i].cantidad+"</td>";html+="   <td>"+POS.currencyFormat(r.datos.compras[i].precio)+"</td>";html+="</tr>";}
html+="   <tr class = ' last Autorizaciones-row ' >";html+="       <td colspan = '5'> Total: "+POS.currencyFormat(r.datos.total)+"</td>";html+="   </tr>";html+="</table>";Ext.getCmp('MermaHtmlPanel').update(html);}
Ext.getBody().unmask();},failure:function(response){POS.error(response);}});};Aplicacion.Autorizaciones.prototype.nueva.numeroCompra=null;Aplicacion.Autorizaciones.prototype.nueva.mermaBuscarCompraBoton=function()
{var values=Aplicacion.Autorizaciones.currentInstance.nueva.mermaPanel.getValues();if(!(values.compra&&/^\d+$/.test(values.compra+''))){Ext.Anim.run(Ext.getCmp('Autorizacion-MermaCompraID'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Autorizaciones.currentInstance.listaDetalleCompra(values.compra)};Aplicacion.Autorizaciones.prototype.nueva.mermaPanel=null;Aplicacion.Autorizaciones.prototype.nueva.mermaPanelCreator=function()
{this.mermaPanel=new Ext.form.FormPanel({scroll:'none',cls:"Tabla",listeners:{"show":function(){}},items:[{xtype:'fieldset',title:'Reportar merma en compra',instructions:'Ingrese el ID de compra.',items:[new Ext.form.Text({id:'Autorizacion-MermaCompraID',name:'compra',label:'ID Compra',listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:Aplicacion.Efectivo.currentInstance.nuevoGastoValidator};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Buscar Compra',margin:15,handler:this.mermaBuscarCompraBoton}),{id:'MermaHtmlPanel',html:null}]});};Aplicacion.Autorizaciones.prototype.solicitudAutorizacionDevolucion=function(values){if(DEBUG){console.log(" Iniciando proceso de solicitud de devolucion de produeto :  ",values);}
Ext.getBody().mask();Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:203,data:Ext.util.JSON.encode(values)},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Aplicacion.Autorizaciones.currentInstance.panelSolicitudDevolucion.hide('pop');if(!r.success)
{Ext.Msg.alert("Autorizaciones","Error: "+r.reason);Ext.getBody().unmask();return;}
Ext.Msg.alert("Autorizaciones","Solicitud enviada con exito.");Ext.getBody().unmask();Aplicacion.Autorizaciones.currentInstance.limpiarDevolucionesPanel();},failure:function(response){POS.error(response);}});}
Aplicacion.Autorizaciones.prototype.solicitarDevolucionVenta=function(id_venta,id_producto,cantidad,cantidad_procesada,descripcion)
{this.solicitarDevolucionVentaPanel=new Ext.form.FormPanel({scroll:'none',items:[{xtype:'fieldset',title:'Reportar devolucion en venta',instructions:'Ingrese la cantidad de Devolución.',id:'Autorizacion-DevolucionVentaPanel-Form',items:[new Ext.form.Text({name:'id_venta',label:'ID Venta',disabled:true,value:id_venta}),new Ext.form.Text({name:'id_producto',label:'ID Producto',disabled:true,value:id_producto}),new Ext.form.Text({name:'cantidadOriginal',value:cantidad,disabled:true,label:'Cantidad  origen'}),new Ext.form.Text({name:'cantidadProcesada',value:cantidad_procesada,disabled:true,label:'Cantidad procesada'}),new Ext.form.Text({id:'Autorizacion-DevolucionVentaPanel-cantidad',name:'cantidadDevuelta',label:'De origen a devolver',disabled:(cantidad)?false:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:null};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Text({id:'Autorizacion-DevolucionVentaPanel-cantidadProcesada',name:'cantidadProcesadaDevuelta',label:'Procesada a devolver',disabled:(cantidad_procesada)?false:true,listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:null};POS.Keyboard.Keyboard(this,kconf);}}}),new Ext.form.Hidden({id:'Autorizacion-DevolucionVentaPanel-descripcion',name:"descripcion",value:descripcion})]}]});var dockedItems=[new Ext.Toolbar({ui:'light',dock:'bottom',items:[new Ext.Button({ui:'back',text:'Regresar',handler:this.limpiarDevolucionesPanel})].concat({xtype:'spacer'}).concat(new Ext.Button({ui:'forward',text:'Enviar Solicitud',handler:this.solicitarDevolucionVentaPanelValidator}))})];this.panelSolicitudDevolucion=new Ext.Panel({dockedItems:dockedItems,centered:true,height:465,width:680,scroll:'none',items:[this.solicitarDevolucionVentaPanel]});sink.Main.ui.setActiveItem(this.panelSolicitudDevolucion,'slide');};Aplicacion.Autorizaciones.prototype.limpiarDevolucionesPanel=function(){Ext.getCmp('DevolucionHtmlPanel').update("");Ext.getCmp('Aurotizacion-devolucionesIdVenta').setValue("");sink.Main.ui.setActiveItem(Aplicacion.Autorizaciones.currentInstance.nueva.devolucionesPanel,'slide');};Aplicacion.Autorizaciones.prototype.solicitarDevolucionVentaPanelValidator=function()
{values=Aplicacion.Autorizaciones.currentInstance.solicitarDevolucionVentaPanel.getValues();if(!Ext.getCmp('Autorizacion-DevolucionVentaPanel-cantidad').isDisabled()){if(isNaN(parseFloat(values.cantidadDevuelta))||parseFloat(values.cantidadDevuelta)<0||parseFloat(values.cantidadDevuelta)>parseFloat(values.cantidadOriginal)){Ext.Anim.run(Ext.getCmp('Autorizacion-DevolucionVentaPanel-cantidad'),'fade',{duration:250,out:true,autoClear:true});return;}}
if(!Ext.getCmp('Autorizacion-DevolucionVentaPanel-cantidadProcesada').isDisabled()){if(isNaN(parseFloat(values.cantidadProcesadaDevuelta))||parseFloat(values.cantidadProcesadaDevuelta)<0||parseFloat(values.cantidadProcesadaDevuelta)>parseFloat(values.cantidadProcesada)){Ext.Anim.run(Ext.getCmp('Autorizacion-DevolucionVentaPanel-cantidadProcesada'),'fade',{duration:250,out:true,autoClear:true});return;}}
if(DEBUG){console.log("enviando solicitud de devolucion",values);}
Aplicacion.Autorizaciones.currentInstance.solicitudAutorizacionDevolucion(values);};Aplicacion.Autorizaciones.prototype.listaDetalleVenta=function(id_venta)
{Ext.getBody().mask('Obteniendo lista de ventas ...','x-mask-loading',true);Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:404,id_venta:id_venta},success:function(response,opts){try{r=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
if(!r.success)
{Ext.getCmp('DevolucionHtmlPanel').update("No se tiene registro de esa venta");Ext.getBody().unmask();}
var html="";if(r.datos.num_ventas==0)
{Ext.getCmp('DevolucionHtmlPanel').update("No se tiene registro del detalle de esa venta");Ext.getBody().unmask();return;}
if(Aplicacion.Autorizaciones.currentInstance.nueva.numeroVenta!=r.datos.id_venta)
{Aplicacion.Autorizaciones.currentInstance.nueva.numeroVenta=r.datos.id_venta;html+="<table border = 0>";html+="   <tr class = 'top'>";html+="       <td>id_venta</td>";html+="       <td>id_producto</td>";html+="       <td>descripcion</td>";html+="       <td>cantidad</td>";html+="       <td>precio</td>";html+="       <td>cantidad procesada</td>";html+="       <td>precio procesada</td>";html+="       <td>subtotal</td>";html+="   </tr>";for(var i=0;i<r.datos.num_ventas;i++)
{html+="<tr class = 'Autorizaciones-row' onClick = ' Aplicacion.Autorizaciones.currentInstance.solicitarDevolucionVenta("+r.datos.id_venta+","+r.datos.ventas[i].id_producto+","+r.datos.ventas[i].cantidad+","+r.datos.ventas[i].cantidad_procesada+","+"\""+r.datos.ventas[i].descripcion+"\""+") ' >";html+="   <td>"+r.datos.id_venta+"</td>";html+="   <td>"+r.datos.ventas[i].id_producto+"</td>";html+="   <td>"+r.datos.ventas[i].descripcion+"</td>";html+="   <td>"+r.datos.ventas[i].cantidad+"</td>";html+="   <td>"+POS.currencyFormat(r.datos.ventas[i].precio)+"</td>";html+="   <td>"+r.datos.ventas[i].cantidad_procesada+"</td>";html+="   <td>"+POS.currencyFormat(r.datos.ventas[i].precio_procesada)+"</td>";html+="   <td>"+POS.currencyFormat((r.datos.ventas[i].cantidad*r.datos.ventas[i].precio)+(r.datos.ventas[i].cantidad_procesada*r.datos.ventas[i].precio_procesada))+"</td>";html+="</tr>";}
html+="   <tr class = ' last Autorizaciones-row ' >";html+="       <td colspan = '8'> Total: "+POS.currencyFormat(r.datos.total)+"</td>";html+="   </tr>";html+="</table>";Ext.getCmp('DevolucionHtmlPanel').update(html);}
Ext.getBody().unmask();},failure:function(response){POS.error(response);}});};Aplicacion.Autorizaciones.prototype.nueva.numeroVenta=null;Aplicacion.Autorizaciones.prototype.nueva.devolucionBuscarVentaBoton=function()
{var values=Aplicacion.Autorizaciones.currentInstance.nueva.devolucionesPanel.getValues();if(!(values.venta&&/^\d+$/.test(values.venta+''))){Ext.Anim.run(Ext.getCmp('Aurotizacion-devolucionesIdVenta'),'fade',{duration:250,out:true,autoClear:true});return;}
Aplicacion.Autorizaciones.currentInstance.listaDetalleVenta(values.venta)};Aplicacion.Autorizaciones.prototype.nueva.devolucionesPanel=null;Aplicacion.Autorizaciones.prototype.nueva.devolucionesPanelCreator=function()
{this.devolucionesPanel=new Ext.form.FormPanel({scroll:'none',cls:"Tabla",listeners:{"show":function(){Aplicacion.Autorizaciones.currentInstance.limpiarDevolucionesPanel();}},items:[{xtype:'fieldset',title:'Autorizar devolucion',instructions:'Seleccione el ID de la venta',items:[new Ext.form.Text({id:'Aurotizacion-devolucionesIdVenta',name:'venta',label:'ID Venta',listeners:{'focus':function(){kconf={type:'num',submitText:'Aceptar',callback:Aplicacion.Efectivo.currentInstance.nuevoGastoValidator};POS.Keyboard.Keyboard(this,kconf);}}})]},new Ext.Button({ui:'action',text:'Buscar Venta',margin:15,handler:this.devolucionBuscarVentaBoton}),{id:'DevolucionHtmlPanel',html:null}]});};Aplicacion.Autorizaciones.prototype.finishedPanel=null;Aplicacion.Autorizaciones.prototype.finishedPanelCreator=function()
{this.finishedPanel=new Ext.Panel({html:""});};Aplicacion.Autorizaciones.prototype.finishedPanelShow=function(productos,empleado)
{this.finishedPanelUpdater(productos,empleado);action="sink.Main.ui.setActiveItem( Aplicacion.Inventario.currentInstance.listaInventarioPanel , 'fade');";setTimeout(action,4000);};Aplicacion.Autorizaciones.prototype.finishedPanelUpdater=function(productos,empleado)
{embarque={productos:null,ticket:null,sucursal:null,empleado:null,impresora:null,leyendasTicket:null}
for(i=0;i<POS.documentos.length;i++){if(POS.documentos[i].documento=='abono_venta_cliente'){var impresora=POS.documentos[i].impresora;break;}}
embarque.productos=productos;embarque.ticket='recepcion_embarque';embarque.sucursal=POS.infoSucursal;embarque.empleado=empleado;embarque.impresora=impresora;embarque.leyendasTicket=POS.leyendasTicket;if(DEBUG){console.log("se mando a imprimir : ",embarque);}
POS.ajaxToClient({module:"Printer",args:embarque,success:function(r){if(DEBUG){console.log("ticket printing responded",r);}},failure:function(){if(DEBUG){console.warn("client not found !!!",r);}},});html="";html+="<table class='Mostrador-ThankYou' style = 'margin : 0 !important;' >";html+=" <tr>";html+="  <td align = center ><img align = center  src='../media/cash_register.png'></td>";html+=" </tr>";html+=" <tr>";html+="  <td align = center> El producto ha sido agregado a su inventario.. </td>";html+=" </tr>";html+="</table>";this.finishedPanel.update(html);sink.Main.ui.setActiveItem(this.finishedPanel,'fade');};Aplicacion.Autorizaciones.prototype.finishedPanelCreator=function()
{this.finishedPanel=new Ext.Panel({html:""});};Ext.regModel('listaDeAutorizacionesModel',{fields:[{name:'id_autorizacion',type:'int'},{name:'estado',type:'int'},{name:'fecha_peticion',convert:function(v,record){return POS.fecha(v);}}]});Aplicacion.Autorizaciones.prototype.listaDeAutorizaciones={lista:null,lastUpdate:null,hash:null};Aplicacion.Autorizaciones.prototype.listaDeAutorizacionesStore=new Ext.data.Store({model:'listaDeAutorizacionesModel',sorters:{property:'id_autorizacion',direction:'DESC'},getGroupString:function(record){json=Ext.util.JSON.decode(record.get('parametros'));return json.descripcion;}});Aplicacion.Autorizaciones.prototype.listaDeAutorizacionesLoad=function(){if(DEBUG){console.log("Actualizando lista de autorizaciones ....");}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:207},success:function(response,opts){try{autorizaciones=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(!autorizaciones.success){return POS.error(autorizaciones);}
this.listaDeAutorizaciones.lista=autorizaciones.payload;this.listaDeAutorizaciones.lastUpdate=Math.round(new Date().getTime()/1000.0);this.listaDeAutorizaciones.hash=autorizaciones.hash;this.listaDeAutorizacionesStore.loadData(autorizaciones.payload);Aplicacion.Autorizaciones.currentInstance.updateListaAutorizaciones();if(DEBUG){console.log("Lista de autorizaciones retrived !",autorizaciones,this.listaDeAutorizacionesStore);}},failure:function(response){POS.error(response);}});};Aplicacion.Autorizaciones.prototype.checkForNewAuts=function(){};Aplicacion.Autorizaciones.prototype.listaDeAutorizacionesPanel=null;Aplicacion.Autorizaciones.prototype.xxx=null;Aplicacion.Autorizaciones.prototype.listaDeAutorizacionesPanelCreator=function(){this.listaDeAutorizacionesPanel=new Ext.Panel({layout:'fit',items:[{xtype:'list',emptyText:"vacio",store:this.listaDeAutorizacionesStore,itemTpl:'<table border=0 >'
+' <tr>'
+'  <td style="width:400px;">Autorizacion numero {id_autorizacion}&nbsp;</td>'
+'  <td style="width:200px;"><span  id="autorizacion_{id_autorizacion}"></span></td>'
+'  <td rowspan=2 style="width:150px;" align=right><img src="../media/arrow2.png" onClick = "Aplicacion.Autorizaciones.currentInstance.detalleAutorizacionPanelShow({id_autorizacion})"></td>'
+' </tr>'
+' <tr>'
+' <td colspan=2><span style="font-size:11px; color: gray;">Enviada el {fecha_peticion}</span></td>'
+'</tr>'
+'</table>',grouped:true,indexBar:false,listeners:{"selectionchange":function(view,nodos,c){view.deselectAll();}}}]});Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel=this.listaDeAutorizacionesPanel;Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel.addListener("show",this.updateListaAutorizaciones)};Aplicacion.Autorizaciones.prototype.updateListaAutorizaciones=function(){if(DEBUG){console.log("actualizando la lista");}
for(var i=0;i<Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesStore.data.items.length;i++){switch(Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesStore.data.items[i].data.estado){case 0:desc="Sin revisar";color="grey";break;case 1:desc="Aceptada";color="green";break;case 2:desc="Rechazada";color="red";break;case 3:desc="En transito";color="blue";break;case 4:desc="Surtido";color="green";break;case 5:desc="Eliminada";color="red";break;case 6:desc="Aplicada";color="green";break;}
upTo=document.createTextNode('( '+desc+' )');var div=document.createElement('span');div.style.color=color;div.appendChild(upTo);if(DEBUG){console.log("vamos a autualizar a : "+upTo);}
var element=document.getElementById('autorizacion_'+Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesStore.data.items[i].data.id_autorizacion);if(element!=null)
{while(element.firstChild){element.removeChild(element.firstChild);}
element.appendChild(div);}}};Aplicacion.Autorizaciones.prototype.surtirAutorizacion=function(aid,productos){autorizacion=Aplicacion.Autorizaciones.currentInstance.detalleAutorizacion;if(DEBUG){console.log("Surtir inventario dada una autorizacion ",aid);}
Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:211,id_autorizacion:aid},success:function(response,opts){try{autorizaciones=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(e);}
if(!autorizaciones.success){Ext.Msg.alert("Autorizaciones","Error: "+autorizaciones.reason);return;}
task();Aplicacion.Autorizaciones.currentInstance.finishedPanelShow(productos,autorizaciones.empleado);},failure:function(response){POS.error(response);}});}
Aplicacion.Autorizaciones.prototype.detalleAutorizacion=null;Aplicacion.Autorizaciones.prototype.detalleAutorizacionFormPanel=null;Aplicacion.Autorizaciones.prototype.detalleAutorizacionPanelShow=function(autorizacion){for(var i=0;i<this.listaDeAutorizacionesStore.data.items.length;i++){if(this.listaDeAutorizacionesStore.data.items[i].data.id_autorizacion==autorizacion)
{autorizacion=this.listaDeAutorizacionesStore.data.items[i].data;break;}}
if(DEBUG){console.log("Mostrando autorizacion : ",autorizacion);}
var parametros=Ext.util.JSON.decode(autorizacion.parametros);if(DEBUG){console.log("------------------------------------");console.log(parametros);console.log("------------------------------------");}
var estado=autorizacion.estado;switch(estado){case 0:estado='No ha sido revisado por el administrador';break;case 1:estado="Autorización aprovada";break;case 2:estado="Autorizacón denegada";break;case 3:estado="Producto en transito";break;case 4:estado="El embarque ha sido surtido";break;case 6:estado="La venta preferencial ya se ha realizado";break;default:estado="Indefinido.";}
if(DEBUG){console.log("El estado de la autorizacion es : ",estado);console.log("Los parametros de la autorizacion son : ",parametros)}
instrucciones=null;var itemsForm=[];if(DEBUG){console.log("La clave de la autorizacion es : ",parametros.clave);}
switch(parametros.clave)
{case'201':itemsForm.push(new Ext.form.Text({label:'ID Autorización',name:'id_autorizacion',value:autorizacion.id_autorizacion}),new Ext.form.Text({label:'Concepto',value:parametros.concepto}),new Ext.form.Text({label:'Monto',value:parametros.monto}));height=375;break;case'202':if(DEBUG){console.log("N");}
itemsForm.push(new Ext.form.Text({label:'ID Autorización',name:'id_autorizacion',value:autorizacion.id_autorizacion}),new Ext.form.Text({label:'Nombre',value:parametros.nombre}),new Ext.form.Text({label:'Cantidad',value:POS.currencyFormat(parametros.cantidad)}));height=375;break;case'203':if(DEBUG){console.log("entre al case 203, parametros : ",parametros);}
parametros.cantidad=parametros.cantidad==0?"0":parametros.cantidad;parametros.cantidad_procesada=parametros.cantidad_procesada==0?"0":parametros.cantidad_procesada;itemsForm.push(new Ext.form.Text({label:'ID Autorización',name:'id_autorizacion',value:autorizacion.id_autorizacion}),new Ext.form.Text({label:'ID Venta',value:parametros.id_venta}),new Ext.form.Text({label:'ID Producto',value:parametros.id_producto}),new Ext.form.Text({label:'Cantidad de origen',value:parametros.cantidad}),new Ext.form.Text({label:'Cantidad procesada',value:parametros.cantidad_procesada}));height=425;break;case'204':itemsForm.push(new Ext.form.Text({label:'ID Autorización',name:'id_autorizacion',value:autorizacion.id_autorizacion}),new Ext.form.Text({label:'Nombre',value:parametros.nombre}));height=360;autorizacion.venta_preferencial=autorizacion.estado==1?true:false;break;case'205':itemsForm.push(new Ext.form.Text({label:'ID Autorización',name:'id_autorizacion',value:autorizacion.id_autorizacion}),new Ext.form.Text({label:'ID Compra',value:parametros.id_compra}),new Ext.form.Text({label:'ID Producto',value:parametros.id_producto}),new Ext.form.Text({label:'Cantidad',value:parametros.cantidad}));height=425;break;case 209:if(DEBUG){console.log("Entre al case 209");}
html="";html+="<table border = 0>";html+="   <tr class = 'top'>";html+="       <td>Producto</td>";html+="       <td>Procesado</td>";html+="       <td>Cantidad</td>";html+="   </tr>";for(i=0;i<parametros.productos.length;i++){var cantidad=parametros.productos[i].procesado==true?parametros.productos[i].cantidad_procesada:parametros.productos[i].cantidad;var procesado=parametros.productos[i].procesado==true?"Si":"No";html+="<tr  >";html+="   <td>"+parametros.productos[i].id_producto+" "+parametros.productos[i].descripcion+"</td>";html+="   <td>"+procesado+"</td>";html+="   <td>"+cantidad+" "+parametros.productos[i].escala+"s</td>";html+="</tr>";}
html+="</table>";itemsForm.push(new Ext.form.Text({label:'Conductor',name:'conductor',value:parametros.conductor}),{id:'detalleAutorizacionFormPanel-Tabla',html:html,cls:'Tabla'});switch(autorizacion.estado)
{case 0:instrucciones="";break;case 3:instrucciones="Hay un embarque en transito con estos productos.";break;default:instrucciones="Usted ya ha recibido este embarque.";}
break;case'210':html="";html+="<table border = 0>";html+="   <tr class = 'top'>";html+="       <td>Producto</td>";html+="       <td>Cantidad Original</td>";html+="       <td>Cantidad Procesada</td>";html+="   </tr>";for(i=0;i<parametros.productos.length;i++){html+="<tr  >";html+="   <td>"+parametros.productos[i].id_producto+" "+parametros.productos[i].descripcion+"</td>";html+="   <td>"+parametros.productos[i].cantidad+" "+parametros.productos[i].escala+"s</td>";html+="   <td>"+parametros.productos[i].cantidad+" "+parametros.productos[i].escala+"s</td>";html+="</tr>";}
html+="</table>";itemsForm.push({id:'detalleAutorizacionFormPanel-Tabla',html:html,cls:'Tabla'});instrucciones="Esta es una solicitud de producto al centro de distribucion.";break;}
Aplicacion.Autorizaciones.currentInstance.detalleAutorizacionFormPanel=new Ext.form.FormPanel({dockedItems:[{dock:'bottom',xtype:'toolbar',items:[{text:'Regresar a lista de autorizaciones',ui:'back',handler:function(){sink.Main.ui.setActiveItem(Aplicacion.Autorizaciones.currentInstance.listaDeAutorizacionesPanel,'slide');}},{xtype:'spacer'},new Ext.Button({ui:'forward',text:'He recibido el embarque',hidden:autorizacion.estado==3?false:true,handler:function(){Aplicacion.Autorizaciones.currentInstance.surtirAutorizacion(autorizacion.id_autorizacion,parametros.productos)}}),new Ext.Button({ui:'forward',text:'Aplicar Venta Preferencial',hidden:autorizacion.venta_preferencial?false:true,handler:function(){Aplicacion.Autorizaciones.currentInstance.seleccionarClientePreferencial(parametros.id_cliente,autorizacion.id_autorizacion);}})]}],items:[{xtype:'fieldset',title:(!parametros.descripcion)?"("+estado+")":parametros.descripcion+".  ("+estado+")",instructions:(instrucciones!=null)?instrucciones:"",items:itemsForm}]});sink.Main.ui.setActiveItem(Aplicacion.Autorizaciones.currentInstance.detalleAutorizacionFormPanel,'slide');};Aplicacion.Autorizaciones.prototype.seleccionarClientePreferencial=function(id_cliente,id_autorizacion){for(var i=0;i<Aplicacion.Clientes.currentInstance.listaDeClientesStore.data.items.length;i++)
{if(Aplicacion.Clientes.currentInstance.listaDeClientesStore.data.items[i].data.id_cliente==id_cliente)
{Aplicacion.Mostrador.currentInstance.carrito.venta_preferencial.cliente=Aplicacion.Clientes.currentInstance.listaDeClientesStore.data.items[i].data;Aplicacion.Mostrador.currentInstance.carrito.venta_preferencial.id_autorizacion=id_autorizacion;Aplicacion.Mostrador.currentInstance.clientePreferencialSeleccionado(Aplicacion.Mostrador.currentInstance.carrito.venta_preferencial.cliente);sink.Main.ui.setActiveItem(Aplicacion.Mostrador.currentInstance.mostradorPanel,'slide');break;}}
if(DEBUG){console.log("se aplico la venta preferencial a el cliente : ",Aplicacion.Mostrador.currentInstance.carrito.venta_preferencial.cliente.nombre);console.log("El carrito contiene : ",Aplicacion.Mostrador.currentInstance.carrito);}};Aplicacion.Autorizaciones.prototype.finalizarAutorizacionVentaPreferencial=function(){Ext.getBody().mask('Modificando estado de la autorizacion de venta preferencial','x-mask-loading',true);carrito=Aplicacion.Mostrador.currentInstance.carrito;Ext.Ajax.request({url:'../proxy.php',scope:this,params:{action:220,id_autorizacion:carrito.venta_preferencial.id_autorizacion},success:function(response,opts){try{autorizacion=Ext.util.JSON.decode(response.responseText);}catch(e){return POS.error(response,e);}
Ext.getBody().unmask();if(!autorizacion.success){if(DEBUG){console.log("Fallo del cambio del estado de la autorizacion ",autorizacion);}
Ext.Msg.alert("Autorizaciones",autorizacion.reason);return;}
carrito.venta_preferencial.cliente=null;carrito.venta_preferencial.id_autorizacion=null;},failure:function(response){POS.error(response);}});};POS.Apps.push(new Aplicacion.Autorizaciones());